project:
  type: website
  output-dir: docs
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for your editing contributions!"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "UMGCCC FCSR"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "Landing"
        href: index.qmd     
    right:
    - icon: youtube
      href: https://www.youtube.com/@CytometryInR
      aria-label: YouTube
    - icon: github
      href: https://github.com/UMGCCCFCSR
      aria-label: GitHub
  sidebar:
    style: floating
    collapse-level: 1
    contents:
    - section: "Tutorial"
      contents:
      - text: "Getting Started"
        href: course/index.qmd
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

